authors:
  medicore:
    name: MediLang Core Team
    description: The core team behind the Medi programming language
    avatar: https://via.placeholder.com/100
    url: https://github.com/MediLang/medi
