repos:
-   repo: local
    hooks:
    -   id: rust-checks
        name: Rust Checks (fmt, clippy, test)
        entry: ./scripts/pre-commit-rust.sh
        language: script
        pass_filenames: false
        always_run: true
        stages: [commit]
        verbose: true
        types: [rust]
