coverage:
  precision: 1
  round: nearest
  range: 60..100

status:
  project:
    default:
      target: 70%
      threshold: 2%
      informational: false
  patch:
    default:
      target: 70%
      threshold: 2%
      informational: false

comment:
  layout: "reach, diff, files"
  behavior: default
  require_changes: false
